#! /usr/bin/python3

import os
import sys
import time

import tides_interpolate


verbose = True if os.getenv('MUNIN_DEBUG') == '1' else False
def verboselog(s):
    if verbose:
        sys.stderr.write('{}: {}\n'.format(plugin_name, s))


def fetch(hostname, portname, timestamp):
    db = '/var/lib/munin/tides_db.sqlite3'
    port_name, ts, height = tides_interpolate.tides_interpolate(db, portname, timestamp)
    print('tide_height.value', height)

def config(hostname, portname):
    print("host_name {}".format(hostname))
    print("graph_title Tide height")
    print("graph_category other")
    print("graph_vlabel Tide height (m)")
    print("tide_height.label Tide height (m)")


_, hostname = sys.argv[0].split('_')
portname = hostname.split('.')[0]

time_ts = time.time()

if len(sys.argv) > 1:
    cmd = sys.argv[1]
    if cmd == 'config':
        config(hostname, portname)
        if True:  # if we support dirtyconfig
            fetch(hostname, portname, time_ts)
        sys.exit(0)

    if cmd == 'suggest':
        sys.exit(0)

    verboselog('unknown argument "{}"'.format(cmd))
    exit(1)

fetch(hostname, portname, time_ts)

